language: java
jdk: oraclejdk8
dist: trusty

# whitelist
branches:
only: master

services:
 - docker
script:
 - cd api 
 - mvn package
 - ls
 - docker build -t woodenwindowbackend --build-arg WAR_FILE .
 - cd ..
after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
 - docker images
 - docker tag woodenwindowbackend $DOCKER_USER/woodenwindowbackend:latest
 - docker push $DOCKER_USER/woodenwindowbackend:latest

deploy:
 provider: elasticbeanstalk
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_ACCESS_KEY
 region: "us-east-1"
 app: "wooden_window"
 env: "WoodenWindow-env"
 bucket_name: "elasticbeanstalk-us-east-1-883500907501"
 on:
  branch: master
