language: java
jdk: oraclejdk8
dist: trusty

# whitelist
branches:
only: master

services:
 - docker
script:
 - mvn install 
 - docker build - < Dockerfile --build-arg WAR_FILE=/target/*.war .
after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
 - docker tag woodenwindowbackend $DOCKER_USER/woodenwindowbackend:$TRAVIS_BUILD_NUMBER
 - docker push $DOCKER_USER/woodenwindowbackend:$TRAVIS_BUILD_NUMBER
 - docker tag woodenwindowbackend $DOCKER_USER/woodenwindowbackend:latest
 - docker push $DOCKER_USER/woodenwindowbackend:latest

deploy:
 provider: elasticbeanstalk
 access_key_id:
  secure: "AWS_ACCESS_KEY"
 secret_access_key:
  secure: "AWS_SECRET_ACCESS_KEY"
 region: "us-east-1"
 app: "Project_2"
 env: "http://project2-env.eba-pmybczpa.us-east-1.elasticbeanstalk.com/"
 bucket_name: "elasticbeanstalk-us-east-1-883500907501"
 on:
  branch: master
