language: java
    jdk: 
    - oraclejdk8

services:
  - docker
before_script:
  -mvn install
script:
  - mvn install mvn run test --watch=false --no-progress
  - docker build -t WoodenWindowBackEnd
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag WoodenWindowBackEnd $DOCKER_USER/WoodenWindowBackEnd:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/WoodenWindowBackEnd:$TRAVIS_BUILD_NUMBER
  - docker tag WoodenWindowBackEnd $DOCKER_USER/WoodenWindowBackEnd:latest
  - docker push $DOCKER_USER/WoodenWindowBackEnd:latest

# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: "ACCESS-KEY-ID"
#   secret_access_key:
#     secure: "SECRET-ACCESS-KEY"
#   region: "us-east-1"
#   app: "Project_2"
#   env: "http://project2-env.eba-pmybczpa.us-east-1.elasticbeanstalk.com/"
#   bucket_name: "elasticbeanstalk-us-east-1-883500907501"
#   on:
#     branch: master
